apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  finalizers:
  - machine.machine.openshift.io
  labels:
    machine.openshift.io/cluster-api-cluster: user01-ops-training-75gjz
    machine.openshift.io/cluster-api-machine-role: master
    machine.openshift.io/cluster-api-machine-type: master
    machine.openshift.io/instance-type: m5.xlarge
    machine.openshift.io/region: eu-north-1
    machine.openshift.io/zone: eu-north-1c
  name: user01-ops-training-75gjz-master-2
  namespace: openshift-machine-api
spec:
  metadata: {}
  providerSpec:
    value:
      ami:
        id: ami-0080eb90a48d9655e
      apiVersion: awsproviderconfig.openshift.io/v1beta1
      blockDevices:
      - ebs:
          encrypted: true
          iops: 0
          kmsKey:
            arn: ""
          volumeSize: 120
          volumeType: gp2
      credentialsSecret:
        name: aws-cloud-credentials
      deviceIndex: 0
      iamInstanceProfile:
        id: user01-ops-training-75gjz-master-profile
      instanceType: m5.xlarge
      kind: AWSMachineProviderConfig
      loadBalancers:
      - name: user01-ops-training-75gjz-int
        type: network
      - name: user01-ops-training-75gjz-ext
        type: network
      metadata:
        creationTimestamp: null
      placement:
        availabilityZone: eu-north-1c
        region: eu-north-1
      securityGroups:
      - filters:
        - name: tag:Name
          values:
          - user01-ops-training-75gjz-master-sg
      subnet:
        filters:
        - name: tag:Name
          values:
          - user01-ops-training-75gjz-private-eu-north-1c
      tags:
      - name: kubernetes.io/cluster/user01-ops-training-75gjz
        value: owned
      - name: customer
        value: acend
      - name: username
        value: user01
      - name: acend-training
        value: ocp4-ops
      userDataSecret:
        name: master-user-data
