configuration:
  backupStorageLocation:
    - provider: aws
      bucket: <username>-ops-training-backup-velero
      config:
        region: us-east-1
  volumeSnapshotLocation:
    - provider: aws
      config:
        region: us-east-1
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
